baseURL = "/"
languageCode = "id-id"
title = "Novel Reading"
buildFuture = true

[outputs]
  home = ["HTML", "JSON"]
  page = []
  section = []
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true